name: Market Data Collection

on:
  schedule:
    # Mon-Fri 9:00 and 16:00 UTC (EST 5:00 AM and 12:00 PM)
    - cron: '0 9,16 * * 1-5'
  workflow_dispatch:  # Manual execution support
    inputs:
      source:
        description: 'Source of the trigger'
        required: false
        default: 'manual'
        type: string

jobs:
  collect-market-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Trigger Market Data Collection
        run: |
          echo "🚀 Starting market data collection..."

          # Determine the source
          if [ "${{ github.event_name }}" = "schedule" ]; then
            SOURCE="github_actions_scheduled"
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            SOURCE="${{ github.event.inputs.source || 'github_actions_manual' }}"
          else
            SOURCE="github_actions_unknown"
          fi

          echo "📊 Collection source: $SOURCE"

          # Call Supabase Edge Function
          response=$(curl -s -w "HTTPSTATUS:%{http_code}" -X POST \
            "${{ secrets.SUPABASE_FUNCTIONS_URL }}/data-collector" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"action\": \"collect_all\", \"source\": \"$SOURCE\"}")

          # Extract HTTP status code and body
          http_code=$(echo "$response" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          body=$(echo "$response" | sed -e 's/HTTPSTATUS\:.*//g')

          echo "📈 HTTP Status: $http_code"
          echo "📋 Response: $body"

          # Check if request was successful
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Market data collection completed successfully"

            # Parse and display results
            collected=$(echo "$body" | jq -r '.collected // "N/A"')
            errors=$(echo "$body" | jq -r '.errors | length // 0')

            echo "📊 Indicators collected: $collected"
            echo "❌ Errors encountered: $errors"

            if [ "$errors" -gt 0 ]; then
              echo "⚠️ Some errors occurred during collection:"
              echo "$body" | jq -r '.errors[]? // empty'
            fi
          else
            echo "❌ Market data collection failed with status $http_code"
            echo "$body"
            exit 1
          fi

      - name: Health Check
        if: always()
        run: |
          echo "🔍 Performing health check..."

          health_response=$(curl -s -w "HTTPSTATUS:%{http_code}" -X POST \
            "${{ secrets.SUPABASE_FUNCTIONS_URL }}/data-collector" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"action": "health"}')

          health_code=$(echo "$health_response" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          health_body=$(echo "$health_response" | sed -e 's/HTTPSTATUS\:.*//g')

          echo "🏥 Health check status: $health_code"
          echo "🏥 Health response: $health_body"

          if [ "$health_code" -eq 200 ]; then
            echo "✅ System health check passed"
          else
            echo "⚠️ System health check failed"
          fi

      - name: Notify on Failure
        if: failure()
        run: |
          echo "🚨 Market data collection workflow failed!"
          echo "📅 Time: $(date -u)"
          echo "🔗 Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Optional: Send notification to Slack/Discord if webhook is configured
          if [ -n "${{ secrets.WEBHOOK_URL }}" ]; then
            curl -X POST "${{ secrets.WEBHOOK_URL }}" \
              -H "Content-Type: application/json" \
              -d "{
                \"text\": \"🚨 Market Data Collection Failed\",
                \"blocks\": [
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"*Market Data Collection Failed*\\n• Time: $(date -u)\\n• Workflow: [View Details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"
                    }
                  }
                ]
              }"
          fi